name: ewallet
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  fl_chart: ^0.64.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

# Configuração do flutter_launcher_icons (DEVE FICAR AQUI - NÍVEL RAIZ)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Ewallet.png"
  min_sdk_version: 21
  # remove_alpha_ios: true  # Descomente se precisar remover transparência no iOS

flutter:
  uses-material-design: true

  # Seção de assets (mantenha dentro da seção flutter)
  assets:
    - assets/Ewallet.png